services:
  db:
    image: postgres:16-alpine
    container_name: taskapi_postgres
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    volumes:
      - taskapi_db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: taskapi_app
    environment:
      SPRING_PROFILES_ACTIVE: postgres
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/taskdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: yourpassword
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
  redis:
    image: redis:7-alpine
    container_name: taskapi_redis
    ports:
      - "6379:6379"
volumes:
  taskapi_db_data:

